# Generated by Django 4.0.6 on 2022-07-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.TextField(default='<i class="fa-solid fa-heart"></i>'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.TextField(default='<i class="fa-solid fa-heart"></i>'),
        ),
    ]
