# Generated by Django 4.0.6 on 2022-07-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.IntegerField(verbose_name='러닝타임'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(verbose_name='개봉년도'),
        ),
    ]
