# Generated by Django 4.0.6 on 2022-07-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('image', models.ImageField(upload_to=None, verbose_name='이미지')),
                ('content', models.TextField(verbose_name='내용')),
                ('interest', models.CharField(max_length=50, verbose_name='관심도')),
                ('devtool', models.CharField(choices=[('RA', 'React'), ('DJ', 'Django'), ('NJ', 'Nodejs')], max_length=50, verbose_name='개발툴')),
            ],
        ),
    ]
