# Generated by Django 4.0.6 on 2022-07-20 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='devtool',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tool', to='posts.tool'),
        ),
        migrations.AlterField(
            model_name='post',
            name='interest',
            field=models.CharField(blank=True, max_length=50, verbose_name='관심도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='content',
            field=models.TextField(blank=True, verbose_name='툴설명'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='툴이름'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='type',
            field=models.CharField(blank=True, max_length=20, verbose_name='툴종류'),
        ),
    ]
