# Generated by Django 4.0.6 on 2022-07-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tool_alter_post_image_alter_post_devtool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='devtool',
            field=models.CharField(max_length=20, verbose_name='개발툴'),
        ),
    ]
